### ISSUE TITLE
The ARGTYPE inconsistent in headers and include

### ISSUE THREAD

**Issue by ztq56** [BeaEngine/beaengine#1]
in headers/BeaEngine.h
> typedef struct  {
   char ArgMnemonic[64];
   Int32 ArgType;
   Int32 ArgSize;
   Int32 ArgPosition;
   UInt32 AccessMode;
   MEMORYTYPE Memory;
   UInt32 SegmentReg;
} ARGTYPE;
#pragma pack()

while in include/baeengine/BaeEngine.h
> #pragma pack(1)
typedef struct  {
   char ArgMnemonic[64];
   UInt64 ArgType;
   Int32 ArgSize;
   Int32 ArgPosition;
   UInt32 AccessMode;
   MEMORYTYPE Memory;
   UInt32 SegmentReg;
} ARGTYPE;
#pragma pack()

which one should I use...
(I think the one in "headers" should be generated by the one in "include")

**Comment by BeaEngine** [comment]
Hi,
ok ! BeaEngine is actually under heavy development. (add last instructions set and improve actual source code) This is a regression introduced in the commit 33a5167a84b3ce39a0f9e0641e93cf3f3b9bf019 . The right value is UInt64 ArgType now ! I fix that tonight. And yes, you are right, there is some bad duplicated code ! This part will be very soon refactored.

**Comment by BeaEngine** [comment]
ok, fixed but as said, this part will be improved to avoid such issues in the future.

**Comment by ztq56** [comment]
thanks and thing goes well now!
