### ISSUE TITLE
ARGUMENTS_TYPE ISSUE

### ISSUE THREAD

**Issue by zhaooptimus** [BeaEngine/beaengine#17]
MEMORY_TYPE = NO_ARGUMENT|REGISTER_TYPE 
this may lead to mistake when use bit test (e.g. Asm.Argument2.ArgType&NO_ARGUMENT)

**Comment by BeaEngine** [comment]
yes. In BeaEngine 5, there are some changes (not yet documented) :
- **ArgumentType** specify the type of the argument. So, in fact, it is not a set of flags anymore. ArgumentType == MEMORY_TYPE is the right check or ArgumentType == REGISTER_TYPE + SSE_REG
- **Registers** is a set of flag specifying the registers used.

**Comment by BeaEngine** [comment]
new changes to make usage of Arguments easier :
 - **Argumentxx.ArgType** : MEMORYTYPE | REGISTER_TYPE | CONSTANT_TYPE | NO_ARGUMENT
 - **Argumentxx.Registers.type** : a set of flags to specify registers type : GENERAL_REG, MMX_REG...
 - **Argumentxx.Registers.gpr** : a set of flags to know which general purpose register is affected (REG0, REG1, REG2...)
 - **Argumentxx.Registers.mmx** : a set of flags to know which MMX register is affected (REG0, REG1, REG2...)
...
