### ISSUE TITLE
unknown instruction xsaveopt

### ISSUE THREAD

**Issue by zhaooptimus** [BeaEngine/beaengine#18]
unknown instruction: xsaveopt

**Comment by BeaEngine** [comment]
Hi,
Yes, xsaveopt & xsaveopt64 are not yet implemented. Actually, I work on implementing all instructions from AVX512. Very soon for XSAVEOPT instructions ! I report the fix here when it is done

**Comment by BeaEngine** [comment]
https://github.com/BeaEngine/beaengine/blob/master/tests/0fae.py
