### ISSUE TITLE
Two stack corruptions

### ISSUE THREAD

**Issue by john-8998** [BeaEngine/beaengine#19]
In Routine_ModRM.c, there are 2 lines with "char str[2],,.", and then sprintf is writing to it 2 chars + NULL termination byte, which currupts the stack.

**Comment by BeaEngine** [comment]
Hi,
ok, thanks for the report. I fix that on saturday

**Comment by BeaEngine** [comment]
quick commit without any test yet, can you tell me if it is ok ?
