### ISSUE TITLE
Disassembly special "pop" instruction has a small problem

### ISSUE THREAD

**Issue by dv0** [BeaEngine/beaengine#2]
For example：pop dword ptr [esp+4].
In this instruction execution is divided into three steps：
    temp  <= [esp]
    esp   <= esp + 4
    [esp + 4]  <= temp
so,in fact the destination address is “[esp+8]”.

**Comment by msaleh83** [comment]
You're right. I'll work on it.
Thanks!

**Comment by BeaEngine** [comment]
ok ok, that's right. let's see how can we solve this specific case.

**Comment by slovene** [comment]
Has this been fixed yet?
