### ISSUE TITLE
Incorrect decoding of vp instructions

### ISSUE THREAD

**Issue by john-8998** [BeaEngine/beaengine#20]
The vp instructions does not decode well.
For example:
"c5 f1 ef c9" should be decoded to "vpxor xmm1,xmm1,xmm1" (instead of "lds...").
"c5 f5 74 01" should be decoded to "vpcmpeqb ymm0,ymm1,ymmword ptr [ecx]" (instead of "lds...").

**Comment by john-8998** [comment]
And now try your code in x86 architecture and see what you get... "lds.." which is wrong.
For example, look at x86 version of ucrtcode.dll!strnlen() which uses a few vp instructions.

**Comment by BeaEngine** [comment]
aah you are right ! if MOD_ == 0x3, VEX is used instead of LDS on 32 bits architecture...my bad. I fix that. Thanks for the report.

**Comment by BeaEngine** [comment]
quick commit without any test yet, can you tell me if it is ok ?
