### ISSUE TITLE
BeaEngine always got wrong address

### ISSUE THREAD

**Issue by peter8777555** [BeaEngine/beaengine#22]
Hi ! Sir,

I use BeaEngine V4 and Delphi 2010.

var
  MyDisasm: TDISASM;

MyDisasm.VirtualAddr:=xxxxxxxx;
MyDisasm.EIP:=xxxxxxxx;

BeaEngine always got wrong address on ALL CALL/JMP/JNE/JE/..........

Why ??

**Comment by pfautrero** [comment]
Sorry for this very late answer...
It seems you did not initialized MyDisasm structure (must be zeroed)

**Comment by peter8777555** [comment]
I have do it below,

var
  MyDisasm: TDISASM;

// ======== Init the TDisasm structure (important !)
FillChar(MyDisasm, SizeOf(TDISASM), 0);
