### ISSUE TITLE
Incorrect decode for vaddss with 3 registers

### ISSUE THREAD

**Issue by EricGrange** [BeaEngine/beaengine#26]
vaddss with 3 xmm registers is decoded with the last register as a memory access, for instance

`c5 fa 58 c4             vaddss xmm0,xmm0,xmm4`

is disassembled as 

`vaddss xmm0, xmm0, dword ptr [xmm4]`

**Comment by BeaEngine** [comment]
damned ! be refactoring...thanks for the report.
commit Beaengine/beaengine@6b0a417

**Comment by BeaEngine** [comment]
have a look at this new release :
https://github.com/BeaEngine/beaengine/releases/tag/v5.0-beta5

**Comment by EricGrange** [comment]
Fix confirmed in beta5, thanks!
