### ISSUE TITLE
Invalid LockPrefix

### ISSUE THREAD

**Issue by 0vercl0k** [BeaEngine/beaengine#9]
The disassembly of `\xf0\x48\x89\xce\xc3` is `mov rsi, rcx ; ret` when it should be actually be prefixed by the `lock` prefix. I've done a bit of debugging and `BeaEngine` sees the `lock` prefix but tags it as InvalidPrefix.

Also note that `BeaEngine` seems to behave the same way on the same bytes disassembled as x86.

A workaround would be appreciated!

Cheers

**Comment by msaleh83** [comment]
Thanks! .. if you already fixed the issue, you can make a pull request.

**Comment by 0vercl0k** [comment]
I unfortunately haven't explored this issue yet, so I don't have any PR for
this. I'll submit one if I manage to find the root-cause of the issue
though :).

Cheers

2016-03-13 13:11 GMT-07:00 Moustafa Saleh <notifications@github.com>:

**Comment by 0vercl0k** [comment]
Hey @msaleh83 - I've attempted to fix this today with https://github.com/0vercl0k/beaengine/commit/d2e0cc354c6f55d7e49a9f3ac8f4c440f0fb83d3 & https://github.com/0vercl0k/beaengine/commit/4859e2d61a41bac1d0440a9e7af2e6aad9ed94cb ; let me know if you feel those look good and I'll submit a PR.

Cheers
